//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.JointControl
{
    [Serializable]
    public class Joint_listMsg : Message
    {
        public const string k_RosMessageName = "joint_control/joint_list";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public Std.Float32MultiArrayMsg[] data;

        public Joint_listMsg()
        {
            this.header = new HeaderMsg();
            this.data = new Std.Float32MultiArrayMsg[0];
        }

        public Joint_listMsg(HeaderMsg header, Std.Float32MultiArrayMsg[] data)
        {
            this.header = header;
            this.data = data;
        }

        public static Joint_listMsg Deserialize(MessageDeserializer deserializer) => new Joint_listMsg(deserializer);

        private Joint_listMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, Std.Float32MultiArrayMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "Joint_listMsg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
